# Generated by Django 5.1.1 on 2024-09-15 21:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='SlotUpdater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('error', models.BooleanField(default=False)),
                ('error_text', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Обновление',
                'verbose_name_plural': 'Обновления',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('work_time', models.CharField(max_length=100)),
                ('accepts_qr', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.SmallIntegerField(default=-1)),
                ('unique_f', models.CharField(editable=False, max_length=100, unique=True)),
                ('dt', models.DateTimeField(default=datetime.datetime.now)),
                ('box_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='wb.boxtype')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='wb.warehouse')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
                'ordering': [],
            },
        ),
    ]
