# Generated by Django 5.1.1 on 2024-09-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='orders', to='wb.warehouse'),
        ),
    ]
